name: Main

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'

    - name: Initialize Flutter
      uses: subosito/flutter-action@v1.3.2
      with:
        flutter-version: 1.17.4

    - run: flutter pub get

    - name: Build APK
      run: flutter build apk
  
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'

    - name: Initialize Flutter
      uses: subosito/flutter-action@v1.3.2
      with:
        flutter-version: 1.17.4

    - run: flutter pub get

    - name: Run tests
      run: flutter test
  
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'

    - name: Initialize Flutter
      uses: subosito/flutter-action@v1.3.2
      with:
        flutter-version: 1.17.4

    - run: flutter pub get

    - name: Run linter
      run: flutter analyze
